import { AlertCircle, ArrowRight, Eye, EyeOff, ShieldCheck, Stethoscope } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [show, setShow] = useState(false)
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const user = await login(form); navigate(location.state?.from || (user.role === 'doctor' ? '/veterinary' : '/dashboard'), { replace: true }) } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to connect. Check that the API is running.') } finally { setBusy(false) } }
  return <AuthFrame title="Welcome back" description="Sign in to access your secure BoviCare workspace."><form onSubmit={submit} className="mt-7 space-y-4"><TextField label="Email address" type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /><Password value={form.password} show={show} setShow={setShow} onChange={event => setForm({ ...form, password: event.target.value })} />{error && <AuthError>{error}</AuthError>}<button disabled={busy} className="button-primary w-full">{busy ? 'Signing in…' : <>Sign in <ArrowRight size={17} /></>}</button></form><p className="mt-6 text-center text-sm text-slate-600">New to BoviCare? <Link className="font-bold text-emerald-700" to="/register">Create an account</Link></p></AuthFrame>
}

export function RegisterPage() {
  const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'farmer' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [show, setShow] = useState(false)
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const user = await register(form); navigate(user.role === 'doctor' ? '/veterinary' : '/dashboard', { replace: true }) } catch (requestError) { const detail = requestError.response?.data?.detail; setError(typeof detail === 'string' ? detail : 'Registration failed. Check your information and try again.') } finally { setBusy(false) } }
  return <AuthFrame title="Create your account" description="Choose your role to set up the correct BoviCare workspace."><form onSubmit={submit} className="mt-7 space-y-4"><TextField label="Full name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /><TextField label="Email address" type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /><label className="block"><span className="label">Role</span><select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })} className="input"><option value="farmer">Farmer</option><option value="doctor">Veterinary doctor</option></select></label><Password value={form.password} show={show} setShow={setShow} onChange={event => setForm({ ...form, password: event.target.value })} help="At least 8 characters, including a letter and number." />{error && <AuthError>{error}</AuthError>}<button disabled={busy} className="button-primary w-full">{busy ? 'Creating account…' : <>Create account <ArrowRight size={17} /></>}</button></form><p className="mt-6 text-center text-sm text-slate-600">Already have an account? <Link className="font-bold text-emerald-700" to="/login">Sign in</Link></p></AuthFrame>
}
function AuthFrame({ title, description, children }) { return <div className="grid min-h-screen lg:grid-cols-[.9fr_1.1fr]"><aside className="hidden bg-emerald-950 p-12 text-white lg:block"><Link to="/" className="flex items-center gap-2 text-xl font-bold"><span className="rounded-xl bg-emerald-400 p-2 text-emerald-950"><Stethoscope size={21} /></span>BoviCare AI</Link><div className="mt-32 max-w-md"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Secure clinical access</p><h2 className="mt-4 text-4xl font-bold leading-tight">Thoughtful technology for cattle health.</h2><p className="mt-5 leading-7 text-emerald-100">Secure role-based access keeps farmer case data private while giving veterinary doctors the context they need.</p></div><div className="mt-16 flex items-center gap-3 text-sm text-emerald-200"><ShieldCheck />JWT-secured API access</div></aside><main className="flex items-center justify-center bg-[#f7faf7] p-5"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/50 sm:p-9"><Link to="/" className="inline-flex items-center gap-2 font-bold text-emerald-900 lg:hidden"><Stethoscope size={19} />BoviCare AI</Link><h1 className="mt-7 text-3xl font-bold tracking-tight text-emerald-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>{children}</div></main></div> }
function TextField({ label, help, ...props }) { return <label className="block"><span className="label">{label}</span><input {...props} className="input" />{help && <span className="mt-1 block text-xs text-slate-500">{help}</span>}</label> }
function Password({ value, onChange, show, setShow, help }) { return <label className="block"><span className="label">Password</span><span className="relative block"><input required minLength="8" type={show ? 'text' : 'password'} value={value} onChange={onChange} className="input pr-11" /><button type="button" onClick={() => setShow(!show)} className="absolute bottom-2.5 right-3 text-slate-400">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></span>{help && <span className="mt-1 block text-xs text-slate-500">{help}</span>}</label> }
function AuthError({ children }) { return <p className="flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={17} />{children}</p> }
